# Script mode (cmake -P): write OUTPUT, a header defining OSC_REVISION as the
# source tree's `git describe --always --dirty` ("unknown" outside git).
#
# Run at every build (the osc_revision target), so the revision never goes
# stale as commits land. The header is rewritten only when the revision
# changes, so an unchanged one recompiles nothing.
#
#   cmake -DSOURCE_DIR=<repo> -DOUTPUT=<header> -P OscRevision.cmake

execute_process(
    COMMAND git describe --always --dirty
    WORKING_DIRECTORY "${SOURCE_DIR}"
    OUTPUT_VARIABLE revision
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE result
    ERROR_QUIET)
if(NOT result EQUAL 0 OR revision STREQUAL "")
    set(revision "unknown")
endif()

set(content "// Generated by cmake/OscRevision.cmake: do not edit.\n#define OSC_REVISION \"${revision}\"\n")
set(old "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" old)
endif()
if(NOT old STREQUAL content)
    file(WRITE "${OUTPUT}" "${content}")
endif()
